### ISSUE TITLE
Facing issue with Mi Notebook 14 I3 10th gen

### ISSUE THREAD

**Issue by AtharvShinde** [itsdrnoob/Mi-NoteBook-14-Hackintosh#1]
Thanks For making such a good stable Efi
But there is unexpected Shut Down some time also BT not working and i am unable to hide wifi logo on status bar 
Hope you will help me...

**Comment by itsdrnoob** [comment]
Fixed xD

**Comment by AtharvShinde** [comment]
Dr pro huehuehue

**Comment by itsdrnoob** [comment]
Me noob huehuehue
