### ISSUE TITLE
The internal mic does not work  (i5 Horizon)

### ISSUE THREAD

**Issue by d-kanti** [itsdrnoob/Mi-NoteBook-14-Hackintosh#4]
The internal mic of the device does not work, though i was able to use external mic after using the fix provided. (ComboJack)

**Comment by d-kanti** [comment]
Does internal mic works in the updated efi ? Is thats why you closed the issue ??

**Comment by itsdrnoob** [comment]
it still doesn't work. That's why its closed :)

**Comment by d-kanti** [comment]
Right. Probably it's not gonna work. External is only option

**Comment by itsdrnoob** [comment]
Yeah. And it's already mentioned in the documentation.

**Comment by d-kanti** [comment]
Yep, but i was still hoping, if by any way.... If anything was possible...
