### ISSUE TITLE
Post-Install Files?

### ISSUE THREAD

**Issue by PhantomZNeuroX** [itsdrnoob/Mi-NoteBook-14-Hackintosh#6]
Hey, can someone send me the post-install files, cant see them anymore, pretty sure they were there before

**Comment by TonyPSR** [comment]
With the latest update, you don't need the post install files. Wi-Fi should work out of the box after successful install. During installation, Wi-Fi may not work. It worked for me. But few of my friends had some issues. 

Once installed, that won't be a problem. You can directly connect to Access Points using the macOS's built-in Wi-Fi selector.
