### ISSUE TITLE
Can u pls help me

### ISSUE THREAD

**Issue by ironmanop96** [itsdrnoob/Mi-NoteBook-14-Hackintosh#7]
Hello can u pls help me in buying a laptop for hackintosh?

**Comment by itsdrnoob** [comment]
This might help

https://picklaptop.com/best-hackintosh-laptops/

https://freedom251.com/hackintosh-laptops/

**Comment by d-kanti** [comment]
This issue might be closed....

**Comment by itsdrnoob** [comment]
Yup :)
